'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Message
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AutoSplitHelper_OpenCV.Message", GetType(Message).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Opening file failed. Please create [table1.csv (comma delimited)] under &quot;savefile/&quot;. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg1() As String
            Get
                Return ResourceManager.GetString("msg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Finish or the window doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg10() As String
            Get
                Return ResourceManager.GetString("msg10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Unknown error. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg11() As String
            Get
                Return ResourceManager.GetString("msg11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Image file for reset doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg12() As String
            Get
                Return ResourceManager.GetString("msg12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Image file for reset or the window doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg13() As String
            Get
                Return ResourceManager.GetString("msg13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  There are blank(s) or Not-integer in SettingTab&apos;s table. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg14() As String
            Get
                Return ResourceManager.GetString("msg14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  There are blanks in Position Tab&apos;s table. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg15() As String
            Get
                Return ResourceManager.GetString("msg15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  There are blank(s) or Not-integer in SettingTab&apos;s table or file is left open. Data is deleted... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg16() As String
            Get
                Return ResourceManager.GetString("msg16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Created / Saved. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg17() As String
            Get
                Return ResourceManager.GetString("msg17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Delete? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg18() As String
            Get
                Return ResourceManager.GetString("msg18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Question に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg19() As String
            Get
                Return ResourceManager.GetString("msg19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Opening file failed. Please create [table2.csv (comma delimited)] under &quot;savefile&quot;. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg2() As String
            Get
                Return ResourceManager.GetString("msg2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  already exists. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg20() As String
            Get
                Return ResourceManager.GetString("msg20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  The handle is not acquired. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg21() As String
            Get
                Return ResourceManager.GetString("msg21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1.bmp doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg22() As String
            Get
                Return ResourceManager.GetString("msg22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1.bmp or reset.bmp doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg23() As String
            Get
                Return ResourceManager.GetString("msg23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  There are blank(s) or Not-integer in  Position Tab&apos;s table or file is left open. Data is deleted... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg24() As String
            Get
                Return ResourceManager.GetString("msg24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please fill in the blanks in the table. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg25() As String
            Get
                Return ResourceManager.GetString("msg25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Failed to erase csv file or image folder. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg26() As String
            Get
                Return ResourceManager.GetString("msg26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ※ If you monitor even once, please delete the profile after rebooting this application. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg27() As String
            Get
                Return ResourceManager.GetString("msg27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  There are blanks. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg28() As String
            Get
                Return ResourceManager.GetString("msg28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  You can not enter letters other than numbers. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg29() As String
            Get
                Return ResourceManager.GetString("msg29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Reading failed. The setting is initialized. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg3() As String
            Get
                Return ResourceManager.GetString("msg3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  in progress に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg30() As String
            Get
                Return ResourceManager.GetString("msg30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Waiting に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg31() As String
            Get
                Return ResourceManager.GetString("msg31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Scene change waiting に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg32() As String
            Get
                Return ResourceManager.GetString("msg32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Dark turn waiting に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg33() As String
            Get
                Return ResourceManager.GetString("msg33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Waiting for specified time に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg34() As String
            Get
                Return ResourceManager.GetString("msg34", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Com に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg35() As String
            Get
                Return ResourceManager.GetString("msg35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Exp に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg36() As String
            Get
                Return ResourceManager.GetString("msg36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Enter a profile name. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg37() As String
            Get
                Return ResourceManager.GetString("msg37", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Create a new profile に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg38() As String
            Get
                Return ResourceManager.GetString("msg38", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Loading に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg39() As String
            Get
                Return ResourceManager.GetString("msg39", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Could not confirm the existence of the window. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg4() As String
            Get
                Return ResourceManager.GetString("msg4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  loading.bmp doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg40() As String
            Get
                Return ResourceManager.GetString("msg40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Any Virtual camera device doesn&apos;t exist. Please install the virtual camera device such as SCFF-DSF, Manycam. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg41() As String
            Get
                Return ResourceManager.GetString("msg41", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Canceled. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg42() As String
            Get
                Return ResourceManager.GetString("msg42", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Connect error has occurred, Please relaunch Autosplitter. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg43() As String
            Get
                Return ResourceManager.GetString("msg43", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Video player is not displayed. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg44() As String
            Get
                Return ResourceManager.GetString("msg44", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &quot;Time&quot; column contains non-numeric character string. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg45() As String
            Get
                Return ResourceManager.GetString("msg45", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Virtual camera connection error has occured. Please try reconnecting the virtual camera and relaunching the auto splitter. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg46() As String
            Get
                Return ResourceManager.GetString("msg46", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  You can&apos;t delete Profile &quot;default&quot;. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg47() As String
            Get
                Return ResourceManager.GetString("msg47", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Prease select item in windowtitle list. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg48() As String
            Get
                Return ResourceManager.GetString("msg48", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  I could not find it. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg49() As String
            Get
                Return ResourceManager.GetString("msg49", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please select picture folder. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg5() As String
            Get
                Return ResourceManager.GetString("msg5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please connect with the virtual camera. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg50() As String
            Get
                Return ResourceManager.GetString("msg50", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  A folder with that name already exists. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg51() As String
            Get
                Return ResourceManager.GetString("msg51", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please input size in the ratio of 16 : 9 or 4 : 3. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg52() As String
            Get
                Return ResourceManager.GetString("msg52", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Handle has not been acquired. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg53() As String
            Get
                Return ResourceManager.GetString("msg53", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  It may not be the path of the video file. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg54() As String
            Get
                Return ResourceManager.GetString("msg54", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  The number of image files does not match the number of data in the table. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg6() As String
            Get
                Return ResourceManager.GetString("msg6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Image file doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg7() As String
            Get
                Return ResourceManager.GetString("msg7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  The image file doesn&apos;t exist or the window doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg8() As String
            Get
                Return ResourceManager.GetString("msg8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Finish! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msg9() As String
            Get
                Return ResourceManager.GetString("msg9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  , There is no image に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msga1() As String
            Get
                Return ResourceManager.GetString("msga1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  You attempted to specify a value outside the range. Please set the value to -215 or more. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msga2() As String
            Get
                Return ResourceManager.GetString("msga2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  You attempted to specify a value outside the range. Please set the value to -250 or more. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msga3() As String
            Get
                Return ResourceManager.GetString("msga3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Preview Capturing に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msgb1() As String
            Get
                Return ResourceManager.GetString("msgb1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Preview に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msgb2() As String
            Get
                Return ResourceManager.GetString("msgb2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Preview Capturing (Designation of monitoring range) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msgb3() As String
            Get
                Return ResourceManager.GetString("msgb3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  invalid range. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msgb4() As String
            Get
                Return ResourceManager.GetString("msgb4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Overwrite? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msgb5() As String
            Get
                Return ResourceManager.GetString("msgb5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Question に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msgb6() As String
            Get
                Return ResourceManager.GetString("msgb6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please capture in row selection state. or restart if you monitor or expand table once. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msgb7() As String
            Get
                Return ResourceManager.GetString("msgb7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Connect に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msgc01() As String
            Get
                Return ResourceManager.GetString("msgc01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Disconnect に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property msgc02() As String
            Get
                Return ResourceManager.GetString("msgc02", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
